### ISSUE TITLE
Phrases and death (PART 2) (PART 3 IN BIO) (24)

### ISSUE THREAD

**Issue by Minekey94** [NicknameGG/talking-icons-files#12]
phrases:
Hello Geometry Dash World!
Just don't...
0 buried, 0 found.
I have returned from the afterlife!
We can talk about this please!
Son'na koto wa kitai shite imasendeshita ne?
Use my icon for 200% luck!
You fool, WE ARE IN BRAZIL.
You're going to SEATTLE!
If you wish to defeat me, train for 100 years.
SURPRISE ATTAAAAAAAAAAAACK
Did you see my friend? He was just here.

death messages:
I am ok whit my death.
Bro why though
I found my next target.
There goes my afternoon plans.
Not a talking guy huh?
Makura de jibun o nagutte miro!
I curse you whit -1000% luck!
Inniciating Death Laser...
Did you gain anything from this?
You're a sweat aren't you?
This reminds me of GDW War 0, bad times.
I am Dead

**Comment by NicknameGG** [comment]
Added and fixed some spelling mistakes
