### ISSUE TITLE
Phrases

### ISSUE THREAD

**Issue by yomamamamamama** [NicknameGG/talking-icons-files#13]
Normal phrases:

hello! have you beaten Bloodbath yet?

this comment is hacked. you can't like it.

here before ra- *gets hit with a metal pipe*

tell robtop i said hi!

WHY U NO RATE MY LEVEL ROBTOP >:(

death phrases:

150.16.203.193

WHY DID YOU KILL ME?

TELL MY WIFE I LOVE HER!

OUCH!

oh no i just died!!!

YOU STUPID N-

nah i'd win.

**Comment by NicknameGG** [comment]
Added with some changes
