### ISSUE TITLE
Bio (PART 3) (PART 4 IN COMMENTS) (22)

### ISSUE THREAD

**Issue by Minekey94** [NicknameGG/talking-icons-files#14]
phrases:
I'VE GOT RUBRUB AND MODERN ON MY SIDE!
This isn't that great
You should press that play button.
Look at you trapped behind that screen!
Lalala, nothing can go wrong today!
Also try Disable Main Menu GUI!
I've seen some things.
Hey man! How you doing?
Who even am I?
It's so bright here
You are fuk map

death messages:
There was nothing I could do!!
WAHHH
WHY DID YOU KILL ME
I WAS FRAAAMED
every part about this is wrong.
I hope someone disables you.
I am... appalled!!!
Hey man, not cool man.
I was just gonna give you some advice
It's so dark here, am I dead?
You are fuk map

**Comment by NicknameGG** [comment]
Added !
