### ISSUE TITLE
How To install that?

### ISSUE THREAD

**Issue by SamLeGamerYB** [NicknameGG/talking-icons-files#9]
Hello @NicknameGG i wonder how can we download [this file](https://github.com/NicknameGG/talking-icons-files) (i have already download on Geode) because there is no tutorial.
Please help me...

-SamLeGamerYT

**Comment by Minekey94** [comment]
What are you trying to do?
If you're trying to add quotes thats not how it works

**Comment by NicknameGG** [comment]
Files are automatically downloaded with the mod! They get updated each time you enter the game by making a request.
Did you mean to ask how to add a quote?

**Comment by SamLeGamerYB** [comment]
> Files are automatically downloaded with the mod! They get updated each time you enter the game by making a request. Did you mean to ask how to add a quote?

Yes i mean like add (by custom file) some text by my self because in the Geode "Unzipped" folder it's showing only all your script
↓ (Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\n.talking-icons)
![image](https://github.com/user-attachments/assets/d39cad26-34f6-4534-ae43-ff9d354a08ff)

**Comment by SamLeGamerYB** [comment]
> What are you trying to do? If you're trying to add quotes thats not how it works

If you know can you tell me?

**Comment by NicknameGG** [comment]
Yep exactly like the guy above said. Your game gets the phrases from this repo

However, local phrases are not a bad idea, i could look into implementing them if needed
